"""auto update

Revision ID: ba12aa20fec0
Revises: 
Create Date: 2026-03-08 07:52:45.404819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba12aa20fec0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.String(), nullable=False),
    sa.Column('intensity', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('personal_note', sa.String(), nullable=True),
    sa.Column('is_ignored', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_id'), 'interactions', ['id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('mood', sa.String(), nullable=True),
    sa.Column('mood_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    op.create_table('need_interaction_marks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('person_need_id', sa.Integer(), nullable=False),
    sa.Column('fulfillment', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_need_interaction_marks_id'), 'need_interaction_marks', ['id'], unique=False)
    op.create_table('needs_catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_needs_catalog_id'), 'needs_catalog', ['id'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=True),
    sa.Column('avatar_emoji', sa.String(), nullable=True),
    sa.Column('is_given_garden', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_id'), 'people', ['id'], unique=False)
    op.create_table('person_needs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('need_id', sa.Integer(), nullable=True),
    sa.Column('custom_need_name', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_needs_id'), 'person_needs', ['id'], unique=False)
    op.create_table('reflection_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('reflection_type', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('summary_text', sa.String(), nullable=True),
    sa.Column('highlights', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reflection_summaries_id'), 'reflection_summaries', ['id'], unique=False)
    op.create_table('relationship_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('balance_score', sa.Float(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('needs_score', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(), nullable=True),
    sa.Column('last_interaction_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_scores_id'), 'relationship_scores', ['id'], unique=False)
    op.create_table('shared_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('shared_relationship_id', sa.Integer(), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=True),
    sa.Column('note_text', sa.String(), nullable=False),
    sa.Column('is_ai_suggested', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_notes_id'), 'shared_notes', ['id'], unique=False)
    op.create_table('shared_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('partner_user_id', sa.String(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('partner_person_id', sa.Integer(), nullable=True),
    sa.Column('invite_code', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sharing_mode', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_relationships_id'), 'shared_relationships', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_relationships_id'), table_name='shared_relationships')
    op.drop_table('shared_relationships')
    op.drop_index(op.f('ix_shared_notes_id'), table_name='shared_notes')
    op.drop_table('shared_notes')
    op.drop_index(op.f('ix_relationship_scores_id'), table_name='relationship_scores')
    op.drop_table('relationship_scores')
    op.drop_index(op.f('ix_reflection_summaries_id'), table_name='reflection_summaries')
    op.drop_table('reflection_summaries')
    op.drop_index(op.f('ix_person_needs_id'), table_name='person_needs')
    op.drop_table('person_needs')
    op.drop_index(op.f('ix_people_id'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_needs_catalog_id'), table_name='needs_catalog')
    op.drop_table('needs_catalog')
    op.drop_index(op.f('ix_need_interaction_marks_id'), table_name='need_interaction_marks')
    op.drop_table('need_interaction_marks')
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_interactions_id'), table_name='interactions')
    op.drop_table('interactions')
    # ### end Alembic commands ###
